require:
  - rubocop-performance

AllCops:
  Exclude:
    - bin/**/*
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - web/api.rb
    - spec/**/*

Metrics/AbcSize:
  Enabled: false